# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
# 2.4 is not actually supported by Travis CI :-(
#  - "2.4"
  - "2.5"
  - "2.6"
  - "2.7"
env:
  # numpy 1.2.1 is distributed with RHEL 5 (and who else would still
  # be using Python 2.4 at this point?)
  - NUMPY_VER=1.2.1
  # Currently the latest release:
  - NUMPY_VER=1.6.1
matrix:
  exclude:
    # This old numpy fails to build on Python 2.7:
    - python: 2.7
      env: NUMPY_VER=1.2.1
before_install:
  - mkdir builds
  - pushd builds
  - curl -O http://kent.dl.sourceforge.net/project/numpy/NumPy/${NUMPY_VER}/numpy-${NUMPY_VER}.tar.gz
  - tar xvf numpy-${NUMPY_VER}.tar.gz
  - cd numpy-${NUMPY_VER}
  - python setup.py install
  - popd
install:
  - python setup.py install
script:
  # We change directories to make sure that python won't find the copy
  # of charlton in the source directory.
  - mkdir asdf
  - cd asdf
  - nosetests --all-modules $(python -c "import os; import charlton; print(os.path.dirname(charlton.__file__))")
