# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  # If more versions are added here, they should also be added to the
  # exclude: block below.
  - 2.5
  - 2.6
  - 2.7
env:
  # Hack: we actually test:
  #   - all versions of python with numpy 1.6.1
  #   - python *2.4* with numpy 1.2.1 (this is the RHEL5 configuration)
  # but travis doesn't support python 2.4, and never will:
  #   https://github.com/travis-ci/travis-ci/issues/485
  # So what we do is add 1.2.1 to the build matrix, then exclude it on
  # all-but-one python version, and then for that one version we don't
  # actually use the system python, but instead build 2.4 and use it.
  - NUMPY_VER=1.2.1
  # Currently the latest release:
  - NUMPY_VER=1.6.1
matrix:
  exclude:
    - python: 2.6
      env: NUMPY_VER=1.2.1
    - python: 2.7
      env: NUMPY_VER=1.2.1
before_install:
  - mkdir builds
  - pushd builds
  # This has to be on a single line because of how travis mangles shell script lines before executing them:
  - if [ "${NUMPY_VER}" == "1.2.1" ]; then deactivate; ../.travis-make-py24-virtualenv.sh $PWD/py24-ve; source $PWD/py24-ve/bin/activate; fi
  - curl -O http://kent.dl.sourceforge.net/project/numpy/NumPy/${NUMPY_VER}/numpy-${NUMPY_VER}.tar.gz
  - tar xzf numpy-${NUMPY_VER}.tar.gz
  - pushd numpy-${NUMPY_VER}
  - python setup.py install
  - popd
  - popd
install:
  - python --version
  - python setup.py install
script:
  # We change directories to make sure that python won't find the copy
  # of charlton in the source directory.
  - mkdir empty
  - cd empty
  - nosetests --all-modules $(python -c "import os; import charlton; print(os.path.dirname(charlton.__file__))")
notifications:
  email:
    - njs@pobox.com
