# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  # If more versions are added here, they should also be added to the
  # exclude: block below.
  - 2.5
  - 2.6
  - 2.7
env:
  # Hack: we actually test:
  #   - all versions of python with numpy 1.6.1
  #   - python *2.4* with numpy 1.2.1 (this is the RHEL5 configuration)
  # but travis doesn't support python 2.4, and never will:
  #   https://github.com/travis-ci/travis-ci/issues/485
  # So what we do is add 1.2.1 to the build matrix, then exclude it on
  # all-but-one python version, and then for that one version we don't
  # actually use the system python, but instead build 2.4 and use it.
  - NUMPY_VER=1.2.1
  # Currently the latest release:
  - NUMPY_VER=1.6.2
matrix:
  exclude:
    - python: 2.6
      env: NUMPY_VER=1.2.1
    - python: 2.7
      env: NUMPY_VER=1.2.1
before_install:
  - mkdir builds
  - pushd builds
  # This has to be on a single "virtual line" because of how Travis
  # munges each line before executing it to print out the exit status.
  # It's okay for it to be on multiple physical lines, so long as you remember:
  # - There can't be any leading "-"s
  # - All newlines will be removed, so use ";"s
  - if [ "${NUMPY_VER}" == "1.2.1" ]; then
      deactivate; 
      ../.travis-make-py24-virtualenv.sh $PWD/py24-ve;
      source $PWD/py24-ve/bin/activate;
      pip install nose;
      fi
  - curl -O http://switch.dl.sourceforge.net/project/numpy/NumPy/${NUMPY_VER}/numpy-${NUMPY_VER}.tar.gz
  - tar xzf numpy-${NUMPY_VER}.tar.gz
  - pushd numpy-${NUMPY_VER}
  - python setup.py install
  - popd
  - pip install coverage
  - popd
  - python -V
  - which nosetests
  - python -c 'import numpy; print numpy.__version__'
install:
  - python setup.py install
script:
  # We change directories to make sure that python won't find the copy
  # of charlton in the source directory.
  - mkdir empty
  - cd empty
  - INSTALLDIR=$(python -c "import os; import charlton; print(os.path.dirname(charlton.__file__))")
  # The --exe is because python sometimes marks all installed modules
  # as executable, so without --exe nosetests will just ignore
  # everything. Baffling, but so it goes.
  - coverage run --source=$INSTALLDIR --rcfile=../.coveragerc $(which nosetests) --exe --failure-detail --all-modules $INSTALLDIR
  - coverage report --rcfile=../.coveragerc --show-missing
notifications:
  email:
    - njs@pobox.com
