# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2
  - 3.3
env:
  - NUMPY_VER=1.7.0
before_install:
  - mkdir builds
  - pushd builds
  - pip install http://switch.dl.sourceforge.net/project/numpy/NumPy/${NUMPY_VER}/numpy-${NUMPY_VER}.tar.gz
  - sudo apt-get install libatlas-dev libatlas-base-dev liblapack-dev gfortran
  # Last version with python 2.5 support
  - pip install --use-mirrors scipy==0.11.0
  - pip install --use-mirrors coverage
  # current pandas requires python 2.6+
  # notice the weird inversion here, since for exit values 0 = true, 1 = false
  - if python -c 'import sys; sys.exit(sys.version_info < (2, 6))'; then pip install --use-mirrors pandas; fi
  - popd
  - python -V
  - which nosetests
  - python -c 'import numpy; print(numpy.__version__)'
install:
  - python setup.py install
script:
  # We change directories to make sure that python won't find the copy
  # of patsy in the source directory.
  - mkdir empty
  - cd empty
  - INSTALLDIR=$(python -c "import os; import patsy; print(os.path.dirname(patsy.__file__))")
  - export PYTHONWARNINGS=default PATSY_FORCE_NO_WARNINGS=1
  # The --exe is because python sometimes marks all installed modules
  # as executable, so without --exe nosetests will just ignore
  # everything. Baffling, but so it goes.
  - coverage run --source=$INSTALLDIR --rcfile=../.coveragerc $(which nosetests) --exe --failure-detail --all-modules $INSTALLDIR
  - coverage report --rcfile=../.coveragerc --show-missing
  - python ../tools/check-API-refs.py
notifications:
  email:
    - njs@pobox.com
